### ISSUE TITLE
Exporting with blockquotes causes misformatting of subsequent blocks

### ISSUE THREAD

**Issue by wireframe** [ryanguill/roam-depot-export-formatter#11]
Example:
```
- top element
  - > child with a blockquote
  - This next item will be misformatted
```

Output:
<img width="1844" alt="Screenshot 2023-02-17 at 11 31 23 AM" src="https://user-images.githubusercontent.com/12001/219725216-c286ba5d-11c6-4609-99e2-ec03b74ea77b.png">

**Comment by ryanguill** [comment]
Sorry for the delay on this, I was able to reproduce it, and will look into a fix. I'm not certain how long it will take me to get to it though, but will keep you posted. Thank you for submitting the issue!

**Comment by ryanguill** [comment]
I believe I have a fix for this, have submitted it to roam-depot so you should hopefully see it before too long.
