### ISSUE TITLE
Enhance 'add line break' functionality to work on nested nodes

### ISSUE THREAD

**Issue by shaunagm** [ryanguill/roam-depot-export-formatter#12]
Thanks for making this plugin! It's really great.

Unfortunately the "add line breaks before paragraphs" toggle doesn't work the way I expect in all situations. When I have nested nodes, and get rid of them through "remove bullets" and "flatten indentation", I'd expect "add line breaks before paragraphs?" to add a line break after each paragraph/node. However toggling this seems to have no effect. It does work when there is only one nested level of bullets I'm getting rid of. For example:

![Screenshot from 2023-03-25 20-16-56](https://user-images.githubusercontent.com/1179362/227748484-ba8cea32-3b10-4593-a319-98fd9aabfd43.png)

The node with a single layer of nesting works (provided I toggle "ignore parent node" on):

![success](https://user-images.githubusercontent.com/1179362/227748509-ae2898b7-d07f-43f7-8106-d25e19348109.png)

The nested node doesn't work regardless of whether I'm showing the parent node:

![fail](https://user-images.githubusercontent.com/1179362/227748514-73252d7a-24a6-4e8f-abc3-e3f4984b52b7.png)

I'm guessing you probably weren't even thinking of this use case, but I'd be so thrilled if you added the capability to add line breaks on nested nodes. It's my own fault for writing a 140,000 word novel with Roam using a nested chapter/scene structure without thinking about having to constantly export it. Please save me from myself! 😂 (If it's not too much trouble.)

**Comment by ryanguill** [comment]
Hi there! Glad you are finding the extension useful.

So when I created this feature it was intended that "paragraph" was only top level items, not sub-bulleted items. If you duplicated the input of your last screenshot, I expect it will add a line before each of the highest level nodes. But I will take a look and see if it might break others if we changed this.

To make sure I understand exactly what you are after though: given your last screenshot, you want three lines in the output, with an extra line break between each of those three?

**Comment by shaunagm** [comment]
> To make sure I understand exactly what you are after though: given your last screenshot, you want three lines in the output, with an extra line break between each of those three?

Yes, exactly! 

And just in case it is helpful, I will explain my actual use case (not sure why I generalized before). Feel free to ignore if you think you've got it already. 

I write novels in Roam and need to export them to google docs, pdfs, etc. A given novel has, say, 20 chapters (first level of indentation) and within those 90 nested scenes (second level of indentation) and within those scenes, a variable number of paragraphs (third level of indentation). It is really the paragraph level where I need line breaks (or paragraph indentation would be just as good) so at the most nested level of indentation, rather than the topmost. As such I need to use the exporter an avg of 90 times per export (once per scene) instead of being able to do it just once.

Totally understand if this isn't a reasonable thing for you to add, but I figured I might as well ask. :)

**Comment by ryanguill** [comment]
ok, I think ive got this sorted for you. It will now work I believe like you originally expected - depending on how you remove the parent node and flatten indentation, anything that is not nested will be considered a paragraph and you can add line breaks before it.  I've submitted it to roam-depot, im not sure how long it will take them to accept it, but you should hopefully see this new version before long. Thanks again for the suggestion.

**Comment by shaunagm** [comment]
Awesome, thanks so much! Roam says the app plugin last updated "08 Nov 2022" so it may be a little while, but I look forward to getting to use the new version. :)

**Comment by ryanguill** [comment]
The new version just dropped. Let me know how it goes for you!

**Comment by shaunagm** [comment]
It works perfectly! Thank you so much. Really appreciate you taking the time to add this.
