### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by jagr21** [ryanguill/roam-depot-export-formatter#3]
When you use a dark theme, the plugin interface looks like this.

![Dark mode](https://user-images.githubusercontent.com/67085080/192082660-dde27473-aaaa-437d-afe2-57f588ff21aa.PNG)

**Comment by ryanguill** [comment]
Hi there - can you tell me what dark theme you are using? I don't know how to reproduce this.

**Comment by ryanguill** [comment]
I think this will fix your issue: https://github.com/ryanguill/roam-depot-export-formatter/pull/8

this will go the next time I make a release
