### ISSUE TITLE
Remove Queries

### ISSUE THREAD

**Issue by exydos** [ryanguill/roam-depot-export-formatter#5]
It would be great to have an option of removing Queries.

The Platinum version of this feature would be, to have the option to either remove only the query or the whole bullet point where the query is inside. Here is why:

Some people use Tags to customize their Queries like:
#min-query {{[[query]]: {and:[[ex-A]] [[ex-B]] {not:{or:[[DONE]]}}}}}

The expected Result should be: 
< empty line >

**Comment by ryanguill** [comment]
resolved: https://github.com/ryanguill/roam-depot-export-formatter/pull/6

will go out the next time I push a release.
